### ISSUE TITLE
Says private orbs do not exist

### ISSUE THREAD

**Issue by Gobd** [CircleCI-Public/circleci-yaml-language-server#139]
I am logged in using `circleci setup` but it still says the private orb does not exist. Any advice?

**Comment by rlegan** [comment]
Hi !

Thanks for you feedback.
We already do know this issue, and currently are working on it.
I'll keep you in touch when this is resolved!

Have a good day :)

**Comment by BeFunes** [comment]
Hi @Gobd, we believe this issue originated in the VS Code extension, and is fixed in the latest patch. 
Could you try installing [version 1.9.7](https://marketplace.visualstudio.com/items?itemName=circleci.circleci) and let us know if you still have the same problem?

**Comment by Gobd** [comment]
Updating (and logging in via the extension) has fixed most of it. There is still 1 job from the orb that says "Cannot find declaration for job". This job was added in a version of the orb published December 6, 2022 and there have been a few new releases since then.

**Comment by JulesFaucherre** [comment]
Hello @Gobd, it comes from the fact that we cache the source code of orbs we requested, unfortunately there is no way to clear this cache :/
Little question about this, our caching system stores the orb source with the key being `orbname:orbversion`. Did you make changes on the orb without changing the version?

**Comment by adambiggs** [comment]
I just started seeing this issue with v1.17.0. Is there anything I can try?

**Comment by adambiggs** [comment]
I tried uninstalling/reinstalling the vscode extension, and for a few seconds it seemed to work again - It showed that there was an update available for my private orb.

But then it reverted back to the `Orb does not exist or is private. Authenticate via the VS Code extension to access your private orbs.cci-language-server` :(

**Comment by BeFunes** [comment]
@adambiggs Thank you for flagging this, it's definitely a bug! We'll release a fix ASAP, likely on Monday

**Comment by adambiggs** [comment]
Seems to be working again, thanks @BeFunes!
