### ISSUE TITLE
Apple Silicon resource class needs to be added to the config schema

### ISSUE THREAD

**Issue by ajamespro** [CircleCI-Public/circleci-yaml-language-server#148]
Doesn't look like `macos.m1.large.gen1` has been added to the list of possible `resource_class`es. 

![image](https://user-images.githubusercontent.com/121245612/230628099-a5d0b1ac-c4d5-492d-a9ca-5811e7f1a8f3.png)

Possible places it might need updating:

- [uno](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/6bd5479468c1352fde43e3d22d917f36e46e9782/pkg/services/complete_test.go#L313)
- [dos](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/6bd5479468c1352fde43e3d22d917f36e46e9782/pkg/parser/validate/executor.go#L58)
- [tres](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/4e4fd42d949836319ec6337fc3a5640cc6dd12b8/pkg/services/complete_test.go#L321)
- [quatro](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/4e4fd42d949836319ec6337fc3a5640cc6dd12b8/pkg/parser/validate/executor.go#L60) 
- [cinco](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/a62209b50d517973628e09561b3afc3f3c6dbe3f/publicschema.json#L462)

**Comment by rlegan** [comment]
Hi !

Thank you for your feedback.
It should have been fixed and deployed, reload your vscode window it should work 😄 
Don't hesitate to reopen the ticket if you still have the issue !
