### ISSUE TITLE
Orb marked as unused when only used in property with type "steps"

### ISSUE THREAD

**Issue by fynsta** [CircleCI-Public/circleci-yaml-language-server#218]
An orb is currently marked as unused when it is only used in a property with type "steps". For example, the [Heroku orb](https://circleci.com/developer/orbs/orb/circleci/heroku#jobs-deploy-via-git) uses it for `pre-deploy` and `post-deploy` as can be seen [here](https://github.com/CircleCI-Public/heroku-orb/blob/6ce0432a1c3253c1ff3ce0b727a5e3c17fb21e68/src/jobs/deploy-via-git.yml#L52C1-L53C1), where they just forward these to the steps list.

I don't know if this is a canonic CircleCI type, because I can't find any documentation on it. But in any case, it would be very helpful to support this.

My example usecase:
```yml
- heroku/deploy-via-git:
   post-deploy:
      - jira/notify
```
where `jira` is then shown as being unused.

**Comment by JulesFaucherre** [comment]
Oh! That's a very good point, we don't look at the job parameters to know if an orb is used! Thanks for reporting!

**Comment by JulesFaucherre** [comment]
Hey [this PR](https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/231) addresses the issue. This should be released soon!
Thanks again for reporting!

**Comment by JulesFaucherre** [comment]
By the way really sorry this took a long time to be released but the fix is released now 🎉
