### ISSUE TITLE
Support XCode version 15.0.0

### ISSUE THREAD

**Issue by nickesk** [CircleCI-Public/circleci-yaml-language-server#238]
CircleCI supports XCode 15.0.0 now, but the language server does not appear to have been updated. For example:

```yaml
macos:
  xcode: 15.0.0
```

Gives me the following error in VSCode: 

```json
[{
	"owner": "cci-diag",
	"severity": 8,
	"message": "Invalid Xcode version 15.0.0",
	"source": "cci-language-server" 
}]
```

The full list of supported XCode versions is [here](https://circleci.com/docs/testing-ios/#supported-xcode-versions).

**Comment by abdelDriowya** [comment]
thanks you for reporting.
pr opened : https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/240
