### ISSUE TITLE
Server exits with "No schema defined"

### ISSUE THREAD

**Issue by technomancy** [CircleCI-Public/circleci-yaml-language-server#264]
I've downloaded the latest stable release (0.9.2) for 64-bit Linux on Debian Stable.

When I try to run the language server, instead of starting the server, it exits immediately (with a successful exit code), and the message "No schema defined" (without a newline).

I can see that it accepts a `-schema` option, but for some reason there is no default value configured for this option, and I can't find the documentation that explains what to use here in order to get the language server to start.

**Comment by JulesFaucherre** [comment]
Hey @technomancy!
[Documentation](https://github.com/CircleCI-Public/circleci-yaml-language-server/issues/266) has been added about this option. The value must be the path of the `schema.json` available in the release assets.
