### ISSUE TITLE
Latest Ubuntu images are not recognized by the language server

### ISSUE THREAD

**Issue by mxa0079** [CircleCI-Public/circleci-yaml-language-server#281]
Per documentation here:

https://circleci.com/developer/machine/image/ubuntu-2004

the following image tags are available and valid: 2024.01.2, 2024.01.1, 2023.10.1

However, the extension is marking them as invalid:

![image](https://github.com/CircleCI-Public/circleci-yaml-language-server/assets/432881/46180ede-591c-46ed-a33c-76c7e3fe8c86)

**Comment by mxa0079** [comment]
@JulesFaucherre @jvincent42 - this is an annoyance more than a real issue, but it is still easy to fix. Could you please review the PR?

**Comment by JulesFaucherre** [comment]
Hey closing the issue as [the fix is now released](https://github.com/CircleCI-Public/circleci-yaml-language-server/releases/tag/0.10.0).
Thanks for raising this!
