### ISSUE TITLE
Neovim - client.request commands for setToken and setSelfHostedUrl result is nil

### ISSUE THREAD

**Issue by tomoakley** [CircleCI-Public/circleci-yaml-language-server#285]
I have implemented the functionality for setting the Circle user token and self-hosted URL in my neovim plugin, [PR here](https://github.com/tomoakley/circleci.nvim/pull/14). Annoyingly I am unable to test it because the Circle org I work on has no private contexts/orbs and it's not self-hosted.

However I'd just like to check I've done it correctly; when the client.request command is made, the handler callback in the Lua code has two params - `error` and `result` (and `ctx` and `config`). According to the [Neovim LSP docs](https://neovim.io/doc/user/lsp.html#lsp-handler), `error` is nil if the request completed. And `result` should be defined - if it's `nil` the request failed. When the LSP client attaches when I run it, both these are nil. The [Microsoft docs for language servers](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage) say this shouldn't be the case. 

In the third param in the handler callback (`ctx`), it contains the arguments supplied (`ctx.params.arguments`). These arguments contained the user token and self-hosted URL.

Does my code work? Should the Circle LSP be responding with some result to indicate success - or is it enough that `error` is nil? I looked at `:LspLog` in neovim but it doesn't appear to be sending anything. Are there any other logs I can look at for the Circle LSP?

**Comment by JulesFaucherre** [comment]
Hey @tomoakley, I just opened [a PR](https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/286) to make the returns more pertinent. That being said with the [current implementation](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/fa37bb5993fbeafb9c326e3d11a4f11e790a0460/pkg/server/methods/executeCommand.go#L15-L92), it's in fact unclear whether the command succeeded or failed so you may just want for these changes to be released.
Thanks for raising this :D!

**Comment by tomoakley** [comment]
Awesome, thanks Jules. I will merge my PR now and when a new version is released will check it out. Thanks!

**Comment by JulesFaucherre** [comment]
FYI, looking at the Microsoft docs, it makes sense to return `nil` in case of success, as there is nothing to return here, we'll keep returning `nil` when the command succeeds but you'll be ensured that you'll get an error if any error happens.

**Comment by JulesFaucherre** [comment]
Hey, closing the issue as [the version is now released](https://github.com/CircleCI-Public/circleci-yaml-language-server/releases/tag/0.10.0).
