### ISSUE TITLE
Update Ubuntu Again

### ISSUE THREAD

**Issue by ambroselittle** [CircleCI-Public/circleci-yaml-language-server#304]
Hi, was trying to specify the [latest (current) ubuntu image of `ubuntu-2404:2024.05.1`](https://discuss.circleci.com/t/new-ubuntu-24-04-linux-machine-executor-image/51018/2) and it shows an error in VS Code.

![image](https://github.com/user-attachments/assets/5b6f7b14-2d8b-489b-8221-e4f4aa371367)

So far as I can see, this was last updated [in this release](https://github.com/CircleCI-Public/circleci-yaml-language-server/releases/tag/0.10.1).

Any chance y'all could add some automation to update and publish new tags as they are released? In any case, any idea when this will get added? Is it a regular cadence?

**Comment by cci-jassad** [comment]
Thanks for calling this out @ambroselittle !  Sorry for the delayed reply.  I'm opening a ticket with the team to explore your suggestion around automating the updates.

**Comment by MikeMcC399** [comment]
@cci-jassad 

- It seems that `ubuntu-2204:2024.05.1` was added through https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/307 and is waiting for a release. The last one was in May 2024.
- Time has moved on and now the newer `ubuntu-2204:2024.08.1` is also missing. Please add this add trigger a release.

**Comment by kevin-kortum-trustedshops** [comment]
Got ya covered in #309

**Comment by MikeMcC399** [comment]
@kevin-kortum-trustedshops 

> Got ya covered in #309

- It seems like you're getting no reaction from the CircleCI organization to your PR #309. Is there any explanation for this?

**Comment by kevin-kortum-trustedshops** [comment]
@loderunner wanted to take a look at their ci pipeline as it does not seem to run for my PR. I am basically waiting for a review & approve

**Comment by cci-jassad** [comment]
@MikeMcC399 @kevin-kortum-trustedshops thanks for the engagement and apologies again for our slow response.  We're juggling a lot these days 😓 .   I'm going to direct one of our engineers to help get #309 over the line.

**Comment by kevin-kortum-trustedshops** [comment]
Thanks. We know there is always something going on that is probably more important but you never know until someone writes it down :)

**Comment by MikeMcC399** [comment]
@cci-jassad 

- #309 has been closed in favor of https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/311 however the latest release is still shown as [circleci-yaml-language-server 0.11.1](https://github.com/CircleCI-Public/circleci-yaml-language-server/releases/tag/0.11.1) from May 23, 2024, so the fix is yet to go live it seems.

**Comment by MikeMcC399** [comment]
`ubuntu-2204:2024.05.1` is now recognized in VSCode so this issue should be closed.

`ubuntu-2204:2024.08.1`, which wasn't part of the original issue, is also recognized.

`ubuntu-2204:2024.11.1` is still open, however this one also wasn't part of the original issue.

**Comment by MikeMcC399** [comment]
- https://github.com/CircleCI-Public/circleci-yaml-language-server/issues/316 opened for the missing November 2024 Ubuntu images

**Comment by cci-jassad** [comment]
> `ubuntu-2404:2024.05.1` (and `ubuntu-2204:2024.05.1`) are now recognized in VSCode so this issue should be closed.
> 
> `ubuntu-2204:2024.08.1`, which wasn't part of the original issue, is also recognized.
> 
> `ubuntu-2204:2024.11.1` is still open, however this one also wasn't part of the original issue.

I'm closing this issue per these comments, and we're scheduling an update to address https://github.com/CircleCI-Public/circleci-yaml-language-server/issues/316
